//! Generate TypeScript type definitions from Rust types via ts-rs.
//! Run with: cargo test --features codegen --test ts_export -- --ignored
//! CI step should run this and diff against committed file.

#![cfg(feature = "codegen")]

use std::fs;
use std::path::Path;
use ts_rs::TS;

use stealth_scanner::types::{
    Confidence, Finding, ScanError, ScanErrorKind, ScanOutcome, Severity, Statistics,
};

#[test]
#[ignore]
fn export_typescript_types() {
    let out_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("web/app/lib/types.generated.ts");

    let mut output = String::from("// Auto-generated by ts-rs from Rust types. Do not edit.\n\n");

    output.push_str(&Severity::decl());
    output.push('\n');
    output.push_str(&Confidence::decl());
    output.push('\n');
    output.push_str(&Finding::decl());
    output.push('\n');
    output.push_str(&Statistics::decl());
    output.push('\n');
    output.push_str(&ScanErrorKind::decl());
    output.push('\n');
    output.push_str(&ScanError::decl());
    output.push('\n');
    output.push_str(&ScanOutcome::decl());
    output.push('\n');

    fs::write(&out_path, &output).expect("write types.generated.ts");
    println!("Wrote TypeScript types to {}", out_path.display());
}
